name: CI Test

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2008944@ds.study.iitm.ac.in
        run: echo "Hello, world!"
